server:
  #application:
    #name: car-service
  port: 4444 #443
  forward-headers-strategy: FRAMEWORK
# register service registry (discovery server)
eureka:
  instance:
    hostname: car-service.northeurope.azurecontainer.io
    #prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      #defaultZone: http://user:password@localhost:1111/eureka
      #defaultZone: http://localhost:1111/eureka
      #defaultZone: http://user:password@carrental-registry.northeurope.azurecontainer.io:1111/eureka
      defaultZone: https://carrental-registry.azurewebsites.net:443/eureka
    healthcheck:
      enabled: false
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
spring:
  data:
    mongodb:
      host: caruser-mongo.northeurope.azurecontainer.io
      port: 27017
      authentication-database: admin
      username: root
      password: wRqGzwd7E86ICdfVhKCcEQROSl=5yMoM
      database: car-service
  rabbitmq:
    host: rabbitmqcarrental.northeurope.azurecontainer.io
    username: carrental
    password: IchBinSuper!2
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
  show-sql: true
  h2:
  console:
    enabled: true
jwt:
  header: Authorization
  secret: 3ef572f7769d78d
  expiration: 7200
soapWebservice:
  user: Admin
  password: pa$$w0rd
allow:
  origin: "*"
